pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_credentials')  
        DOCKER_IMAGE = "praveenpeterjay2/miniproj_image1"
        DOCKER_TAG = "1.0"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/PraveenPeterJay/SPE_Mini_Project.git'
            }
        }

        stage('Test') {
            steps {
                dir('SPE_Mini_Project') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'SPE_Mini_Project/**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Build JAR') {
            steps {
                dir('SPE_Mini_Project') {
                    sh 'mvn clean package'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                    dir('SPE_Mini_Project') {
                        sh "docker build -t $DOCKER_IMAGE:$DOCKER_TAG ."
                    }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('SPE_Mini_Project') {
                    sh """
                    echo "$DOCKERHUB_CREDENTIALS_PSW" | docker login -u "$DOCKERHUB_CREDENTIALS_USR" --password-stdin
                    docker push $DOCKER_IMAGE:$DOCKER_TAG
                    docker logout
                    """
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                dir('SPE_Mini_Project') {
                    sh "ansible-playbook -i ansible/hosts ansible/deploy.yml"
                }
            }
        }
    }

    post {
        success {
            echo "Build and deployment completed successfully!"
        }
        failure {
            echo "Build or deployment failed. Check logs above."
        }
    }
}
